# Generated by Django 5.1.1 on 2024-10-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_emailclient_owner_mailings_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailclient',
            options={'ordering': ['owner', 'name'], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ['owner', 'launch_at'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['owner', 'message_title'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
