# Generated by Django 5.1.1 on 2024-10-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_emailclient_options_alter_mailings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ['owner', 'launch_at'], 'permissions': [('change_active_mailing', 'change_active_mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
